{"trial_id": "0", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "num_layers", "default": 1, "conditions": [], "values": [1, 2, 3], "ordered": true}}, {"class_name": "Choice", "config": {"name": "units_0", "default": 32, "conditions": [], "values": [32, 64, 128, 256, 512], "ordered": true}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.005, 0.001], "ordered": true}}, {"class_name": "Choice", "config": {"name": "units_1", "default": 32, "conditions": [], "values": [32, 64, 128, 256, 512], "ordered": true}}], "values": {"num_layers": 2, "units_0": 128, "learning_rate": 0.005, "units_1": 32}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\tonyg\\anaconda3\\envs\\financial_analysis\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 270, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\tonyg\\anaconda3\\envs\\financial_analysis\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 235, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\tonyg\\anaconda3\\envs\\financial_analysis\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 287, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"c:\\Users\\tonyg\\anaconda3\\envs\\financial_analysis\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 214, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"c:\\Users\\tonyg\\anaconda3\\envs\\financial_analysis\\lib\\site-packages\\keras_tuner\\engine\\hypermodel.py\", line 144, in fit\n    return model.fit(*args, **kwargs)\n  File \"c:\\Users\\tonyg\\anaconda3\\envs\\financial_analysis\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\tonyg\\AppData\\Local\\Temp\\__autograph_generated_filef8vow5f2.py\", line 15, in tf__train_function\n    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\nTypeError: in user code:\n\n    File \"c:\\Users\\tonyg\\anaconda3\\envs\\financial_analysis\\lib\\site-packages\\keras\\engine\\training.py\", line 1160, in train_function  *\n        return step_function(self, iterator)\n\n    TypeError: outer_factory.<locals>.inner_factory.<locals>.tf__directional_accuracy() missing 1 required positional argument: 'y_pred'\n\n"}